import { Member } from './member';

export const Members: Member[] = [
    {
      id: 13,
      lastName: 'Thorn',
      firstName: 'Chris',
      middleName: null,
      suffix: null,
      address1: '1601S. Jackson',
      address2: '',
      address3: null,
      city: 'Joplin',
      stateId: 26,
      countryId: 185,
      postalCode: 64804,
      homePhone: '-417',
      cellPhone: '',
      email: null,
      dob: '1976-01-01',
      dojoId: 11,
      memberTypeId: 3,
      dateJoined: '1994-07-01',
      dateOfRank: '2002-11-23',
      rankText: '2nd Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2008-11-01',
      comments: ''
    },
    {
      id: 53,
      lastName: 'Morris',
      firstName: 'Kevin',
      middleName: null,
      suffix: null,
      address1: 'P.O. Box 628',
      address2: null,
      address3: null,
      city: 'Hydesville',
      stateId: 5,
      countryId: 185,
      postalCode: 95547,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: '1956-01-01',
      dojoId: 24,
      memberTypeId: 3,
      dateJoined: '1990-10-01',
      dateOfRank: '2008-06-01',
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2013-10-01',
      comments: null
    },
    {
      id: 63,
      lastName: 'Logan',
      firstName: 'Glen',
      middleName: null,
      suffix: null,
      address1: '11702 E Freedom Dr',
      address2: '',
      address3: null,
      city: 'Clarmore',
      stateId: 37,
      countryId: 185,
      postalCode: 74017,
      homePhone: '918-275-4380',
      cellPhone: '',
      email: null,
      dob: '1952-01-01',
      dojoId: 34,
      memberTypeId: 3,
      dateJoined: '1991-04-01',
      dateOfRank: '2003-01-01',
      rankText: '6th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2011-04-01',
      comments: ''
    },
    {
      id: 66,
      lastName: 'Mead',
      firstName: 'Harold J',
      middleName: null,
      suffix: null,
      address1: '46387 451st Ave',
      address2: null,
      address3: null,
      city: 'Nicollet',
      stateId: 24,
      countryId: 185,
      postalCode: 56074,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: '1945-01-01',
      dojoId: 284,
      memberTypeId: 2,
      dateJoined: '1991-03-20',
      dateOfRank: '2013-06-01',
      rankText: '10th dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2011-02-01',
      comments: null
    },
    {
      id: 82,
      lastName: 'Lee',
      firstName: 'James D.',
      middleName: null,
      suffix: null,
      address1: '1709 Watson Ave',
      address2: null,
      address3: null,
      city: 'Bronx',
      stateId: 33,
      countryId: 185,
      postalCode: 10479,
      homePhone: null,
      cellPhone: '212-640-5438',
      email: null,
      dob: '1962-01-01',
      dojoId: 35,
      memberTypeId: 2,
      dateJoined: '1995-12-01',
      dateOfRank: '2006-12-01',
      rankText: '5th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2013-10-01',
      comments: null
    },
    {
      id: 90,
      lastName: 'Williams',
      firstName: 'Anthony L.',
      middleName: null,
      suffix: null,
      address1: '4645 Cash Road',
      address2: '',
      address3: null,
      city: 'Flowery Branch',
      stateId: 11,
      countryId: 185,
      postalCode: 30542,
      homePhone: '770 (or 404) 9674534',
      cellPhone: '',
      email: null,
      dob: '1964-01-01',
      dojoId: 48,
      memberTypeId: 3,
      dateJoined: '1990-09-27',
      dateOfRank: '2009-06-30',
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2010-02-01',
      comments: ''
    },
    {
      id: 93,
      lastName: 'McFarland',
      firstName: 'Ronald',
      middleName: null,
      suffix: null,
      address1: 'P.O. Box',
      address2: 444,
      address3: null,
      city: 'Oakwood',
      stateId: 11,
      countryId: 185,
      postalCode: 30566,
      homePhone: '770-536-2173',
      cellPhone: '770-945-1919',
      email: null,
      dob: '1974-01-01',
      dojoId: 48,
      memberTypeId: 1,
      dateJoined: '1996-02-01',
      dateOfRank: '2004-12-11',
      rankText: '2nd Kyu',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2010-02-01',
      comments: ''
    },
    {
      id: 119,
      lastName: 'Mizell',
      firstName: 'David',
      middleName: null,
      suffix: null,
      address1: '8625 N.Mattox',
      address2: 'Apt 139',
      address3: null,
      city: 'Kanas City',
      stateId: 26,
      countryId: 185,
      postalCode: 64154,
      homePhone: '913-287-7454',
      cellPhone: '',
      email: null,
      dob: '1954-05-19',
      dojoId: 58,
      memberTypeId: 3,
      dateJoined: '1996-03-01',
      dateOfRank: '2007-06-09',
      rankText: '5th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2009-01-01',
      comments: ''
    },
    {
      id: 124,
      lastName: 'Dodson',
      firstName: 'Tom',
      middleName: null,
      suffix: null,
      address1: '702 M St. N.W.',
      address2: '',
      address3: null,
      city: 'Miami',
      stateId: 37,
      countryId: 185,
      postalCode: 74375,
      homePhone: 9185425975,
      cellPhone: 'None',
      email: null,
      dob: '1996-01-01',
      dojoId: 59,
      memberTypeId: 1,
      dateJoined: '1995-03-01',
      dateOfRank: '2000-09-07',
      rankText: '2nd Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2009-04-01',
      comments: ''
    },
    {
      id: 232,
      lastName: 'Whitehead',
      firstName: 'Tony',
      middleName: null,
      suffix: null,
      address1: 'P.O. Box 673',
      address2: null,
      address3: null,
      city: 'Scotia',
      stateId: 5,
      countryId: 185,
      postalCode: 95565,
      homePhone: null,
      cellPhone: 'None',
      email: null,
      dob: '1969-08-20',
      dojoId: 24,
      memberTypeId: 1,
      dateJoined: '2004-03-29',
      dateOfRank: '2008-06-07',
      rankText: '4th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2013-10-01',
      comments: null
    },
    {
      id: 249,
      lastName: 'Pryor',
      firstName: 'Justin',
      middleName: null,
      suffix: null,
      address1: 'P.O. Box 615',
      address2: null,
      address3: null,
      city: 'Scotia',
      stateId: 5,
      countryId: 185,
      postalCode: 95565,
      homePhone: null,
      cellPhone: 'None',
      email: null,
      dob: '1987-02-10',
      dojoId: 24,
      memberTypeId: 1,
      dateJoined: '1995-02-01',
      dateOfRank: '2002-12-14',
      rankText: '1st Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2006-11-01',
      comments: null
    },
    {
      id: 263,
      lastName: 'McEntire',
      firstName: 'Monty M.',
      middleName: null,
      suffix: null,
      address1: '449 W. 2nd St.',
      address2: 'P.O. Box 374',
      address3: null,
      city: 'Booneville',
      stateId: 4,
      countryId: 185,
      postalCode: 72927,
      homePhone: '501-675-5910',
      cellPhone: 'None',
      email: null,
      dob: '1956-01-01',
      dojoId: 4,
      memberTypeId: 1,
      dateJoined: '1996-04-15',
      dateOfRank: '1996-04-15',
      rankText: '5th Kyu',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2010-05-01',
      comments: ''
    },
    {
      id: 270,
      lastName: 'Atchley',
      firstName: 'Kirk Jason',
      middleName: null,
      suffix: null,
      address1: '76 Riviera Dr.',
      address2: '',
      address3: null,
      city: 'Booneville',
      stateId: 4,
      countryId: 185,
      postalCode: 72927,
      homePhone: '501-675-3457',
      cellPhone: 'None',
      email: null,
      dob: '1986-01-01',
      dojoId: 4,
      memberTypeId: 1,
      dateJoined: '1996-04-15',
      dateOfRank: '2001-04-01',
      rankText: 'Shodan-Ho',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2006-05-01',
      comments: ''
    },
    {
      id: 274,
      lastName: 'Duff',
      firstName: 'Charles R.',
      middleName: null,
      suffix: null,
      address1: '4822 E. State Hwy KK',
      address2: null,
      address3: null,
      city: 'Fair Grove',
      stateId: 26,
      countryId: 185,
      postalCode: 65648,
      homePhone: null,
      cellPhone: '417-864-0176',
      email: null,
      dob: '1949-11-29',
      dojoId: 300,
      memberTypeId: 1,
      dateJoined: '1989-11-01',
      dateOfRank: '2014-09-05',
      rankText: '8th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2009-01-01',
      comments: null
    },
    {
      id: 275,
      lastName: 'Duff',
      firstName: 'Jared R.',
      middleName: null,
      suffix: null,
      address1: '4822 E. State Hwy KK',
      address2: null,
      address3: null,
      city: 'Fair Grove',
      stateId: 26,
      countryId: 185,
      postalCode: 65648,
      homePhone: null,
      cellPhone: 'None',
      email: null,
      dob: '1974-07-10',
      dojoId: 300,
      memberTypeId: 1,
      dateJoined: '1990-01-01',
      dateOfRank: '1999-05-04',
      rankText: '3rd Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2009-01-01',
      comments: null
    },
    {
      id: 276,
      lastName: 'Duff',
      firstName: 'Mathew A.',
      middleName: null,
      suffix: null,
      address1: '4822 E. State Hwy KK',
      address2: null,
      address3: null,
      city: 'Fair Grove',
      stateId: 26,
      countryId: 185,
      postalCode: 65648,
      homePhone: null,
      cellPhone: 'None',
      email: null,
      dob: '1976-02-08',
      dojoId: 300,
      memberTypeId: 1,
      dateJoined: '1990-01-01',
      dateOfRank: '1996-10-22',
      rankText: 'Shodan-Ho',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2009-11-01',
      comments: null
    },
    {
      id: 277,
      lastName: 'Duff',
      firstName: 'Erik C.',
      middleName: null,
      suffix: null,
      address1: '4822 E. State Hwy KK',
      address2: null,
      address3: null,
      city: 'Fair Grove',
      stateId: 26,
      countryId: 185,
      postalCode: 65648,
      homePhone: null,
      cellPhone: 'None',
      email: null,
      dob: '1980-09-08',
      dojoId: 300,
      memberTypeId: 1,
      dateJoined: '1990-01-01',
      dateOfRank: '2008-06-03',
      rankText: '2nd Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2009-01-01',
      comments: null
    },
    {
      id: 312,
      lastName: 'Murrill',
      firstName: 'Dan',
      middleName: null,
      suffix: null,
      address1: '677 Indian Valley',
      address2: null,
      address3: null,
      city: 'Ozark',
      stateId: 26,
      countryId: 185,
      postalCode: 65721,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: '1951-07-28',
      dojoId: 79,
      memberTypeId: 3,
      dateJoined: '2000-01-30',
      dateOfRank: '2013-08-01',
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2006-02-01',
      comments: null
    },
    {
      id: 392,
      lastName: 'Cannon',
      firstName: 'Russell H',
      middleName: null,
      suffix: null,
      address1: 'RR2 Box 70',
      address2: '',
      address3: null,
      city: 'Fairfax',
      stateId: 37,
      countryId: 185,
      postalCode: 74637,
      homePhone: '918 6423118',
      cellPhone: '',
      email: null,
      dob: '1944-09-09',
      dojoId: 87,
      memberTypeId: 3,
      dateJoined: '1997-01-01',
      dateOfRank: '2010-12-01',
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2010-01-01',
      comments: ''
    },
    {
      id: 396,
      lastName: 'Looney',
      firstName: 'Johnny',
      middleName: null,
      suffix: null,
      address1: '750 Central Ave',
      address2: null,
      address3: null,
      city: 'South Williamson',
      stateId: 18,
      countryId: 185,
      postalCode: 41570,
      homePhone: null,
      cellPhone: 6062370026,
      email: null,
      dob: '1961-02-13',
      dojoId: 89,
      memberTypeId: 3,
      dateJoined: '1997-01-01',
      dateOfRank: '2014-05-01',
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2014-01-01',
      comments: null
    },
    {
      id: 417,
      lastName: 'Giacomini',
      firstName: 'Kalee',
      middleName: null,
      suffix: null,
      address1: '',
      address2: '',
      address3: null,
      city: '',
      stateId: 5,
      countryId: 185,
      postalCode: '',
      homePhone: '',
      cellPhone: '',
      email: null,
      dob: null,
      dojoId: 24,
      memberTypeId: 1,
      dateJoined: '1990-12-01',
      dateOfRank: '2009-06-26',
      rankText: '3rd Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2006-11-01',
      comments: ''
    },
    {
      id: 451,
      lastName: 'Mizell',
      firstName: 'Dee',
      middleName: null,
      suffix: null,
      address1: '',
      address2: '',
      address3: null,
      city: '',
      stateId: 26,
      countryId: 185,
      postalCode: '',
      homePhone: '',
      cellPhone: '',
      email: null,
      dob: null,
      dojoId: 58,
      memberTypeId: 1,
      dateJoined: '1997-02-01',
      dateOfRank: '2005-02-18',
      rankText: '3rd Kyu',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2010-02-01',
      comments: ''
    },
    {
      id: 458,
      lastName: 'Meyer',
      firstName: 'Robert',
      middleName: null,
      suffix: null,
      address1: null,
      address2: null,
      address3: null,
      city: null,
      stateId: 26,
      countryId: 185,
      postalCode: null,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: null,
      dojoId: 56,
      memberTypeId: 1,
      dateJoined: '1997-02-01',
      dateOfRank: '1996-09-01',
      rankText: '4th Kyu',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2014-01-01',
      comments: null
    },
    {
      id: 594,
      lastName: 'Mashburn',
      firstName: 'Victor',
      middleName: null,
      suffix: null,
      address1: '',
      address2: '',
      address3: null,
      city: '',
      stateId: 37,
      countryId: 185,
      postalCode: '',
      homePhone: '',
      cellPhone: '',
      email: null,
      dob: null,
      dojoId: 87,
      memberTypeId: 1,
      dateJoined: '1997-05-01',
      dateOfRank: '2006-05-31',
      rankText: '5th Kyu',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2006-01-01',
      comments: ''
    },
    {
      id: 654,
      lastName: 'Hamparian',
      firstName: 'Mark',
      middleName: null,
      suffix: null,
      address1: '3 third st',
      address2: null,
      address3: null,
      city: 'Garden city Park',
      stateId: 33,
      countryId: 185,
      postalCode: 1104,
      homePhone: null,
      cellPhone: '631-774-4248',
      email: null,
      dob: null,
      dojoId: 86,
      memberTypeId: 3,
      dateJoined: '1993-10-01',
      dateOfRank: '1994-06-11',
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2001-09-01',
      comments: null
    },
    {
      id: 841,
      lastName: 'Harper',
      firstName: 'Steven',
      middleName: null,
      suffix: null,
      address1: '',
      address2: '',
      address3: null,
      city: '',
      stateId: 49,
      countryId: 185,
      postalCode: '',
      homePhone: '',
      cellPhone: '',
      email: null,
      dob: null,
      dojoId: 102,
      memberTypeId: 1,
      dateJoined: '1998-06-01',
      dateOfRank: '2004-05-01',
      rankText: 'Shodan-Ho',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2007-02-01',
      comments: ''
    },
    {
      id: 889,
      lastName: 'Williams',
      firstName: 'Luke',
      middleName: null,
      suffix: null,
      address1: '',
      address2: '',
      address3: null,
      city: '',
      stateId: 11,
      countryId: 185,
      postalCode: '',
      homePhone: '',
      cellPhone: '',
      email: null,
      dob: null,
      dojoId: 48,
      memberTypeId: 1,
      dateJoined: '1998-11-01',
      dateOfRank: '2009-06-30',
      rankText: '2nd Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2010-02-01',
      comments: ''
    },
    {
      id: 983,
      lastName: 'McKelvy',
      firstName: 'Allan',
      middleName: null,
      suffix: null,
      address1: '',
      address2: '',
      address3: null,
      city: '',
      stateId: 26,
      countryId: 185,
      postalCode: '',
      homePhone: '',
      cellPhone: '',
      email: null,
      dob: null,
      dojoId: 68,
      memberTypeId: 3,
      dateJoined: '1999-05-01',
      dateOfRank: '2007-06-09',
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2010-05-01',
      comments: ''
    },
    {
      id: 1009,
      lastName: 'Rigney',
      firstName: 'Rick',
      middleName: null,
      suffix: null,
      address1: null,
      address2: null,
      address3: null,
      city: null,
      stateId: 17,
      countryId: 185,
      postalCode: null,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: null,
      dojoId: 31,
      memberTypeId: 1,
      dateJoined: '1999-06-01',
      dateOfRank: '1999-06-05',
      rankText: '1st Kyu',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2006-11-01',
      comments: null
    },
    {
      id: 1043,
      lastName: 'Brock',
      firstName: 'Mickey J',
      middleName: null,
      suffix: null,
      address1: null,
      address2: null,
      address3: null,
      city: null,
      stateId: 11,
      countryId: 185,
      postalCode: null,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: null,
      dojoId: 272,
      memberTypeId: 1,
      dateJoined: '1999-09-01',
      dateOfRank: '2009-09-01',
      rankText: '6th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: '2013-09-01',
      comments: null
    }
  ];