namespace Ncma.Repository.Models.SeedData
{
    public static class CountrySeedData
    {
        public static Country[] SeedData => new[] {
            new Country {  Id = 1, Name = "Afghanistan" },
            new Country {  Id = 2, Name = "Albania" },
            new Country {  Id = 3, Name = "Algeria" },
            new Country {  Id = 4, Name = "Andorra" },
            new Country {  Id = 5, Name = "Antigua and Barbuda" },
            new Country {  Id = 6, Name = "Argentina" },
            new Country {  Id = 7, Name = "Armenia" },
            new Country {  Id = 8, Name = "Australia" },
            new Country {  Id = 9, Name = "Austria" },
            new Country {  Id = 10, Name = "Azerbaijan" },
            new Country {  Id = 11, Name = "Bahamas" },
            new Country {  Id = 12, Name = "Bahrain" },
            new Country {  Id = 13, Name = "Bangladesh" },
            new Country {  Id = 14, Name = "Barbados" },
            new Country {  Id = 15, Name = "Belarus" },
            new Country {  Id = 16, Name = "Belgium" },
            new Country {  Id = 17, Name = "Belize" },
            new Country {  Id = 18, Name = "Benin" },
            new Country {  Id = 19, Name = "Bhutan" },
            new Country {  Id = 20, Name = "Bolivia" },
            new Country {  Id = 21, Name = "Bosnia and Herzegovina" },
            new Country {  Id = 22, Name = "Botswana" },
            new Country {  Id = 23, Name = "Brazil" },
            new Country {  Id = 24, Name = "Brunei" },
            new Country {  Id = 25, Name = "Bulgaria" },
            new Country {  Id = 26, Name = "Burkina Faso" },
            new Country {  Id = 27, Name = "Burundi" },
            new Country {  Id = 28, Name = "Cambodia" },
            new Country {  Id = 29, Name = "Cameroon" },
            new Country {  Id = 30, Name = "Canada" },
            new Country {  Id = 31, Name = "Cape Verde" },
            new Country {  Id = 32, Name = "Central African Republic" },
            new Country {  Id = 33, Name = "Chad" },
            new Country {  Id = 34, Name = "Chile" },
            new Country {  Id = 35, Name = "China" },
            new Country {  Id = 36, Name = "Colombia" },
            new Country {  Id = 37, Name = "Comoros" },
            new Country {  Id = 38, Name = "Congo" },
            new Country {  Id = 39, Name = "Costa Rica" },
            new Country {  Id = 40, Name = "Cote dIvoire" },
            new Country {  Id = 41, Name = "Croatia" },
            new Country {  Id = 42, Name = "Cuba" },
            new Country {  Id = 43, Name = "Cyprus" },
            new Country {  Id = 44, Name = "Czech Republic" },
            new Country {  Id = 45, Name = "Denmark" },
            new Country {  Id = 46, Name = "Djibouti" },
            new Country {  Id = 47, Name = "Dominica" },
            new Country {  Id = 48, Name = "Dominican Republic" },
            new Country {  Id = 49, Name = "East Timor" },
            new Country {  Id = 50, Name = "Ecuador" },
            new Country {  Id = 51, Name = "Egypt" },
            new Country {  Id = 52, Name = "El Salvador" },
            new Country {  Id = 53, Name = "Equatorial Guinea" },
            new Country {  Id = 54, Name = "Eritrea" },
            new Country {  Id = 55, Name = "Estonia" },
            new Country {  Id = 56, Name = "Ethiopia" },
            new Country {  Id = 57, Name = "Fiji" },
            new Country {  Id = 58, Name = "Finland" },
            new Country {  Id = 59, Name = "France" },
            new Country {  Id = 60, Name = "Gabon" },
            new Country {  Id = 61, Name = "Gambia" },
            new Country {  Id = 62, Name = "Georgia" },
            new Country {  Id = 63, Name = "Germany" },
            new Country {  Id = 64, Name = "Ghana" },
            new Country {  Id = 65, Name = "Greece" },
            new Country {  Id = 66, Name = "Grenada" },
            new Country {  Id = 67, Name = "Guatemala" },
            new Country {  Id = 68, Name = "Guinea" },
            new Country {  Id = 69, Name = "Guinea-Bissau" },
            new Country {  Id = 70, Name = "Guyana" },
            new Country {  Id = 71, Name = "Haiti" },
            new Country {  Id = 72, Name = "Honduras" },
            new Country {  Id = 73, Name = "Hong Kong" },
            new Country {  Id = 74, Name = "Hungary" },
            new Country {  Id = 75, Name = "Iceland" },
            new Country {  Id = 76, Name = "India" },
            new Country {  Id = 77, Name = "Indonesia" },
            new Country {  Id = 78, Name = "Iran" },
            new Country {  Id = 79, Name = "Iraq" },
            new Country {  Id = 80, Name = "Ireland" },
            new Country {  Id = 81, Name = "Israel" },
            new Country {  Id = 82, Name = "Italy" },
            new Country {  Id = 83, Name = "Jamaica" },
            new Country {  Id = 84, Name = "Japan" },
            new Country {  Id = 85, Name = "Jordan" },
            new Country {  Id = 86, Name = "Kazakhstan" },
            new Country {  Id = 87, Name = "Kenya" },
            new Country {  Id = 88, Name = "Kiribati" },
            new Country {  Id = 89, Name = "North Korea" },
            new Country {  Id = 90, Name = "South Korea" },
            new Country {  Id = 91, Name = "Kuwait" },
            new Country {  Id = 92, Name = "Kyrgyzstan" },
            new Country {  Id = 93, Name = "Laos" },
            new Country {  Id = 94, Name = "Latvia" },
            new Country {  Id = 95, Name = "Lebanon" },
            new Country {  Id = 96, Name = "Lesotho" },
            new Country {  Id = 97, Name = "Liberia" },
            new Country {  Id = 98, Name = "Libya" },
            new Country {  Id = 99, Name = "Liechtenstein" },
            new Country {  Id = 100, Name = "Lithuania" },
            new Country {  Id = 101, Name = "Luxembourg" },
            new Country {  Id = 102, Name = "Macedonia" },
            new Country {  Id = 103, Name = "Madagascar" },
            new Country {  Id = 104, Name = "Malawi" },
            new Country {  Id = 105, Name = "Malaysia" },
            new Country {  Id = 106, Name = "Maldives" },
            new Country {  Id = 107, Name = "Mali" },
            new Country {  Id = 108, Name = "Malta" },
            new Country {  Id = 109, Name = "Marshall Islands" },
            new Country {  Id = 110, Name = "Mauritania" },
            new Country {  Id = 111, Name = "Mauritius" },
            new Country {  Id = 112, Name = "Mexico" },
            new Country {  Id = 113, Name = "Micronesia" },
            new Country {  Id = 114, Name = "Moldova" },
            new Country {  Id = 115, Name = "Monaco" },
            new Country {  Id = 116, Name = "Mongolia" },
            new Country {  Id = 117, Name = "Montenegro" },
            new Country {  Id = 118, Name = "Morocco" },
            new Country {  Id = 119, Name = "Mozambique" },
            new Country {  Id = 120, Name = "Myanmar" },
            new Country {  Id = 121, Name = "Namibia" },
            new Country {  Id = 122, Name = "Nauru" },
            new Country {  Id = 123, Name = "Nepal" },
            new Country {  Id = 124, Name = "Netherlands" },
            new Country {  Id = 125, Name = "New Zealand" },
            new Country {  Id = 126, Name = "Nicaragua" },
            new Country {  Id = 127, Name = "Niger" },
            new Country {  Id = 128, Name = "Nigeria" },
            new Country {  Id = 129, Name = "Norway" },
            new Country {  Id = 130, Name = "Oman" },
            new Country {  Id = 131, Name = "Pakistan" },
            new Country {  Id = 132, Name = "Palau" },
            new Country {  Id = 133, Name = "Panama" },
            new Country {  Id = 134, Name = "Papua New Guinea" },
            new Country {  Id = 135, Name = "Paraguay" },
            new Country {  Id = 136, Name = "Peru" },
            new Country {  Id = 137, Name = "Philippines" },
            new Country {  Id = 138, Name = "Poland" },
            new Country {  Id = 139, Name = "Portugal" },
            new Country {  Id = 140, Name = "Puerto Rico" },
            new Country {  Id = 141, Name = "Qatar" },
            new Country {  Id = 142, Name = "Romania" },
            new Country {  Id = 143, Name = "Russia" },
            new Country {  Id = 144, Name = "Rwanda" },
            new Country {  Id = 145, Name = "Saint Kitts and Nevis" },
            new Country {  Id = 146, Name = "Saint Lucia" },
            new Country {  Id = 147, Name = "Saint Vincent and the Grenadines" },
            new Country {  Id = 148, Name = "Samoa" },
            new Country {  Id = 149, Name = "San Marino" },
            new Country {  Id = 150, Name = "Sao Tome and Principe" },
            new Country {  Id = 151, Name = "Saudi Arabia" },
            new Country {  Id = 152, Name = "Senegal" },
            new Country {  Id = 153, Name = "Serbia and Montenegro" },
            new Country {  Id = 154, Name = "Seychelles" },
            new Country {  Id = 155, Name = "Sierra Leone" },
            new Country {  Id = 156, Name = "Singapore" },
            new Country {  Id = 157, Name = "Slovakia" },
            new Country {  Id = 158, Name = "Slovenia" },
            new Country {  Id = 159, Name = "Solomon Islands" },
            new Country {  Id = 160, Name = "Somalia" },
            new Country {  Id = 161, Name = "South Africa" },
            new Country {  Id = 162, Name = "Spain" },
            new Country {  Id = 163, Name = "Sri Lanka" },
            new Country {  Id = 164, Name = "Sudan" },
            new Country {  Id = 165, Name = "Suriname" },
            new Country {  Id = 166, Name = "Swaziland" },
            new Country {  Id = 167, Name = "Sweden" },
            new Country {  Id = 168, Name = "Switzerland" },
            new Country {  Id = 169, Name = "Syria" },
            new Country {  Id = 170, Name = "Taiwan" },
            new Country {  Id = 171, Name = "Tajikistan" },
            new Country {  Id = 172, Name = "Tanzania" },
            new Country {  Id = 173, Name = "Thailand" },
            new Country {  Id = 174, Name = "Togo" },
            new Country {  Id = 175, Name = "Tonga" },
            new Country {  Id = 176, Name = "Trinidad and Tobago" },
            new Country {  Id = 177, Name = "Tunisia" },
            new Country {  Id = 178, Name = "Turkey" },
            new Country {  Id = 179, Name = "Turkmenistan" },
            new Country {  Id = 180, Name = "Tuvalu" },
            new Country {  Id = 181, Name = "Uganda" },
            new Country {  Id = 182, Name = "Ukraine" },
            new Country {  Id = 183, Name = "United Arab Emirates" },
            new Country {  Id = 184, Name = "United Kingdom" },
            new Country {  Id = 185, Name = "United States" },
            new Country {  Id = 186, Name = "Uruguay" },
            new Country {  Id = 187, Name = "Uzbekistan" },
            new Country {  Id = 188, Name = "Vanuatu" },
            new Country {  Id = 189, Name = "Vatican City" },
            new Country {  Id = 190, Name = "Venezuela" },
            new Country {  Id = 191, Name = "Vietnam" },
            new Country {  Id = 192, Name = "Yemen" },
            new Country {  Id = 193, Name = "Zambia" },
            new Country {  Id = 194, Name = "Zimbabwe" },
        };
    }
}
