namespace Ncma.Repository.Models.SeedData
{
    public static class StateSeedData
    {
        public static State[] SeedData => new[] {
            new State { Id = 1, StateName = "Alabama", StateAbbrev = "AL" },
            new State { Id = 2, StateName = "Alaska", StateAbbrev = "AK" },
            new State { Id = 3, StateName = "Arizona", StateAbbrev = "AZ" },
            new State { Id = 4, StateName = "Arkansas", StateAbbrev = "AR" },
            new State { Id = 5, StateName = "California", StateAbbrev = "CA" },
            new State { Id = 6, StateName = "Colorado", StateAbbrev = "CO" },
            new State { Id = 7, StateName = "Connecticut", StateAbbrev = "CT" },
            new State { Id = 8, StateName = "Delaware", StateAbbrev = "DE" },
            new State { Id = 9, StateName = "District of Columbia", StateAbbrev = "DC" },
            new State { Id = 10, StateName = "Florida", StateAbbrev = "FL" },
            new State { Id = 11, StateName = "Georgia", StateAbbrev = "GA" },
            new State { Id = 12, StateName = "Hawaii", StateAbbrev = "HI" },
            new State { Id = 13, StateName = "Idaho", StateAbbrev = "ID" },
            new State { Id = 14, StateName = "Illinois", StateAbbrev = "IL" },
            new State { Id = 15, StateName = "Indiana", StateAbbrev = "IN" },
            new State { Id = 16, StateName = "Iowa", StateAbbrev = "IA" },
            new State { Id = 17, StateName = "Kansas", StateAbbrev = "KS" },
            new State { Id = 18, StateName = "Kentucky", StateAbbrev = "KY" },
            new State { Id = 19, StateName = "Louisiana", StateAbbrev = "LA" },
            new State { Id = 20, StateName = "Maine", StateAbbrev = "ME" },
            new State { Id = 21, StateName = "Maryland", StateAbbrev = "MD" },
            new State { Id = 22, StateName = "Massachusetts", StateAbbrev = "MA" },
            new State { Id = 23, StateName = "Michigan", StateAbbrev = "MI" },
            new State { Id = 24, StateName = "Minnesota", StateAbbrev = "MN" },
            new State { Id = 25, StateName = "Mississippi", StateAbbrev = "MS" },
            new State { Id = 26, StateName = "Missouri", StateAbbrev = "MO" },
            new State { Id = 27, StateName = "Montana", StateAbbrev = "MT" },
            new State { Id = 28, StateName = "Nebraska", StateAbbrev = "NE" },
            new State { Id = 29, StateName = "Nevada", StateAbbrev = "NV" },
            new State { Id = 30, StateName = "New Hampshire", StateAbbrev = "NH" },
            new State { Id = 31, StateName = "New Jersey", StateAbbrev = "NJ" },
            new State { Id = 32, StateName = "New Mexico", StateAbbrev = "NM" },
            new State { Id = 33, StateName = "New York", StateAbbrev = "NY" },
            new State { Id = 34, StateName = "North Carolina", StateAbbrev = "NC" },
            new State { Id = 35, StateName = "North Dakota", StateAbbrev = "ND" },
            new State { Id = 36, StateName = "Ohio", StateAbbrev = "OH" },
            new State { Id = 37, StateName = "Oklahoma", StateAbbrev = "OK" },
            new State { Id = 38, StateName = "Oregon", StateAbbrev = "OR" },
            new State { Id = 39, StateName = "Pennsylvania", StateAbbrev = "PA" },
            new State { Id = 40, StateName = "Rhode Island", StateAbbrev = "RI" },
            new State { Id = 41, StateName = "South Carolina", StateAbbrev = "SC" },
            new State { Id = 42, StateName = "South Dakota", StateAbbrev = "SD" },
            new State { Id = 43, StateName = "Tennessee", StateAbbrev = "TN" },
            new State { Id = 44, StateName = "Texas", StateAbbrev = "TX" },
            new State { Id = 45, StateName = "Utah", StateAbbrev = "UT" },
            new State { Id = 46, StateName = "Vermont", StateAbbrev = "VT" },
            new State { Id = 47, StateName = "Virginia", StateAbbrev = "VA" },
            new State { Id = 48, StateName = "Washington", StateAbbrev = "WA" },
            new State { Id = 49, StateName = "West Virginia", StateAbbrev = "WV" },
            new State { Id = 50, StateName = "Wisconsin", StateAbbrev = "WI" },
            new State { Id = 51, StateName = "Wyoming", StateAbbrev = "WY" },
            new State { Id = 52, StateName = "Alberta", StateAbbrev = "AB" },
            new State { Id = 53, StateName = "British Columbia", StateAbbrev = "BC" },
            new State { Id = 54, StateName = "Manitoba", StateAbbrev = "MB" },
            new State { Id = 55, StateName = "Newfoundland", StateAbbrev = "NL" },
            new State { Id = 56, StateName = "New Brunswick", StateAbbrev = "NB" },
            new State { Id = 57, StateName = "Nova Scotia", StateAbbrev = "NS" },
            new State { Id = 58, StateName = "Northwest Territories", StateAbbrev = "NT" },
            new State { Id = 59, StateName = "Nunavut", StateAbbrev = "NU" },
            new State { Id = 60, StateName = "Ontario", StateAbbrev = "ON" },
            new State { Id = 61, StateName = "Prince Edward Island", StateAbbrev = "PE" },
            new State { Id = 62, StateName = "Quebec", StateAbbrev = "QC" },
            new State { Id = 63, StateName = "Saskatchewan", StateAbbrev = "SK" },
            new State { Id = 64, StateName = "Yukon Territory", StateAbbrev = "YT" }
        };
    }
}
