import { Country } from './country';

export const Countries: Country[]  = [
    {  id:  1, name:  'Afghanistan' },
    {  id:  2, name:  'Albania' },
    {  id:  3, name:  'Algeria' },
    {  id:  4, name:  'Andorra' },
    {  id:  5, name:  'Antigua and Barbuda' },
    {  id:  6, name:  'Argentina' },
    {  id:  7, name:  'Armenia' },
    {  id:  8, name:  'Australia' },
    {  id:  9, name:  'Austria' },
    {  id:  10, name:  'Azerbaijan' },
    {  id:  11, name:  'Bahamas' },
    {  id:  12, name:  'Bahrain' },
    {  id:  13, name:  'Bangladesh' },
    {  id:  14, name:  'Barbados' },
    {  id:  15, name:  'Belarus' },
    {  id:  16, name:  'Belgium' },
    {  id:  17, name:  'Belize' },
    {  id:  18, name:  'Benin' },
    {  id:  19, name:  'Bhutan' },
    {  id:  20, name:  'Bolivia' },
    {  id:  21, name:  'Bosnia and Herzegovina' },
    {  id:  22, name:  'Botswana' },
    {  id:  23, name:  'Brazil' },
    {  id:  24, name:  'Brunei' },
    {  id:  25, name:  'Bulgaria' },
    {  id:  26, name:  'Burkina Faso' },
    {  id:  27, name:  'Burundi' },
    {  id:  28, name:  'Cambodia' },
    {  id:  29, name:  'Cameroon' },
    {  id:  30, name:  'Canada' },
    {  id:  31, name:  'Cape Verde' },
    {  id:  32, name:  'Central African Republic' },
    {  id:  33, name:  'Chad' },
    {  id:  34, name:  'Chile' },
    {  id:  35, name:  'China' },
    {  id:  36, name:  'Colombia' },
    {  id:  37, name:  'Comoros' },
    {  id:  38, name:  'Congo' },
    {  id:  39, name:  'Costa Rica' },
    {  id:  40, name:  'Cote dIvoire' },
    {  id:  41, name:  'Croatia' },
    {  id:  42, name:  'Cuba' },
    {  id:  43, name:  'Cyprus' },
    {  id:  44, name:  'Czech Republic' },
    {  id:  45, name:  'Denmark' },
    {  id:  46, name:  'Djibouti' },
    {  id:  47, name:  'Dominica' },
    {  id:  48, name:  'Dominican Republic' },
    {  id:  49, name:  'East Timor' },
    {  id:  50, name:  'Ecuador' },
    {  id:  51, name:  'Egypt' },
    {  id:  52, name:  'El Salvador' },
    {  id:  53, name:  'Equatorial Guinea' },
    {  id:  54, name:  'Eritrea' },
    {  id:  55, name:  'Estonia' },
    {  id:  56, name:  'Ethiopia' },
    {  id:  57, name:  'Fiji' },
    {  id:  58, name:  'Finland' },
    {  id:  59, name:  'France' },
    {  id:  60, name:  'Gabon' },
    {  id:  61, name:  'Gambia' },
    {  id:  62, name:  'Georgia' },
    {  id:  63, name:  'Germany' },
    {  id:  64, name:  'Ghana' },
    {  id:  65, name:  'Greece' },
    {  id:  66, name:  'Grenada' },
    {  id:  67, name:  'Guatemala' },
    {  id:  68, name:  'Guinea' },
    {  id:  69, name:  'Guinea-Bissau' },
    {  id:  70, name:  'Guyana' },
    {  id:  71, name:  'Haiti' },
    {  id:  72, name:  'Honduras' },
    {  id:  73, name:  'Hong Kong' },
    {  id:  74, name:  'Hungary' },
    {  id:  75, name:  'Iceland' },
    {  id:  76, name:  'India' },
    {  id:  77, name:  'Indonesia' },
    {  id:  78, name:  'Iran' },
    {  id:  79, name:  'Iraq' },
    {  id:  80, name:  'Ireland' },
    {  id:  81, name:  'Israel' },
    {  id:  82, name:  'Italy' },
    {  id:  83, name:  'Jamaica' },
    {  id:  84, name:  'Japan' },
    {  id:  85, name:  'Jordan' },
    {  id:  86, name:  'Kazakhstan' },
    {  id:  87, name:  'Kenya' },
    {  id:  88, name:  'Kiribati' },
    {  id:  89, name:  'North Korea' },
    {  id:  90, name:  'South Korea' },
    {  id:  91, name:  'Kuwait' },
    {  id:  92, name:  'Kyrgyzstan' },
    {  id:  93, name:  'Laos' },
    {  id:  94, name:  'Latvia' },
    {  id:  95, name:  'Lebanon' },
    {  id:  96, name:  'Lesotho' },
    {  id:  97, name:  'Liberia' },
    {  id:  98, name:  'Libya' },
    {  id:  99, name:  'Liechtenstein' },
    {  id:  100, name:  'Lithuania' },
    {  id:  101, name:  'Luxembourg' },
    {  id:  102, name:  'Macedonia' },
    {  id:  103, name:  'Madagascar' },
    {  id:  104, name:  'Malawi' },
    {  id:  105, name:  'Malaysia' },
    {  id:  106, name:  'Maldives' },
    {  id:  107, name:  'Mali' },
    {  id:  108, name:  'Malta' },
    {  id:  109, name:  'Marshall Islands' },
    {  id:  110, name:  'Mauritania' },
    {  id:  111, name:  'Mauritius' },
    {  id:  112, name:  'Mexico' },
    {  id:  113, name:  'Micronesia' },
    {  id:  114, name:  'Moldova' },
    {  id:  115, name:  'Monaco' },
    {  id:  116, name:  'Mongolia' },
    {  id:  117, name:  'Montenegro' },
    {  id:  118, name:  'Morocco' },
    {  id:  119, name:  'Mozambique' },
    {  id:  120, name:  'Myanmar' },
    {  id:  121, name:  'Namibia' },
    {  id:  122, name:  'Nauru' },
    {  id:  123, name:  'Nepal' },
    {  id:  124, name:  'Netherlands' },
    {  id:  125, name:  'New Zealand' },
    {  id:  126, name:  'Nicaragua' },
    {  id:  127, name:  'Niger' },
    {  id:  128, name:  'Nigeria' },
    {  id:  129, name:  'Norway' },
    {  id:  130, name:  'Oman' },
    {  id:  131, name:  'Pakistan' },
    {  id:  132, name:  'Palau' },
    {  id:  133, name:  'Panama' },
    {  id:  134, name:  'Papua New Guinea' },
    {  id:  135, name:  'Paraguay' },
    {  id:  136, name:  'Peru' },
    {  id:  137, name:  'Philippines' },
    {  id:  138, name:  'Poland' },
    {  id:  139, name:  'Portugal' },
    {  id:  140, name:  'Puerto Rico' },
    {  id:  141, name:  'Qatar' },
    {  id:  142, name:  'Romania' },
    {  id:  143, name:  'Russia' },
    {  id:  144, name:  'Rwanda' },
    {  id:  145, name:  'Saint Kitts and Nevis' },
    {  id:  146, name:  'Saint Lucia' },
    {  id:  147, name:  'Saint Vincent and the Grenadines' },
    {  id:  148, name:  'Samoa' },
    {  id:  149, name:  'San Marino' },
    {  id:  150, name:  'Sao Tome and Principe' },
    {  id:  151, name:  'Saudi Arabia' },
    {  id:  152, name:  'Senegal' },
    {  id:  153, name:  'Serbia and Montenegro' },
    {  id:  154, name:  'Seychelles' },
    {  id:  155, name:  'Sierra Leone' },
    {  id:  156, name:  'Singapore' },
    {  id:  157, name:  'Slovakia' },
    {  id:  158, name:  'Slovenia' },
    {  id:  159, name:  'Solomon Islands' },
    {  id:  160, name:  'Somalia' },
    {  id:  161, name:  'South Africa' },
    {  id:  162, name:  'Spain' },
    {  id:  163, name:  'Sri Lanka' },
    {  id:  164, name:  'Sudan' },
    {  id:  165, name:  'Suriname' },
    {  id:  166, name:  'Swaziland' },
    {  id:  167, name:  'Sweden' },
    {  id:  168, name:  'Switzerland' },
    {  id:  169, name:  'Syria' },
    {  id:  170, name:  'Taiwan' },
    {  id:  171, name:  'Tajikistan' },
    {  id:  172, name:  'Tanzania' },
    {  id:  173, name:  'Thailand' },
    {  id:  174, name:  'Togo' },
    {  id:  175, name:  'Tonga' },
    {  id:  176, name:  'Trinidad and Tobago' },
    {  id:  177, name:  'Tunisia' },
    {  id:  178, name:  'Turkey' },
    {  id:  179, name:  'Turkmenistan' },
    {  id:  180, name:  'Tuvalu' },
    {  id:  181, name:  'Uganda' },
    {  id:  182, name:  'Ukraine' },
    {  id:  183, name:  'United Arab Emirates' },
    {  id:  184, name:  'United Kingdom' },
    {  id:  185, name:  'United States' },
    {  id:  186, name:  'Uruguay' },
    {  id:  187, name:  'Uzbekistan' },
    {  id:  188, name:  'Vanuatu' },
    {  id:  189, name:  'Vatican City' },
    {  id:  190, name:  'Venezuela' },
    {  id:  191, name:  'Vietnam' },
    {  id:  192, name:  'Yemen' },
    {  id:  193, name:  'Zambia' },
    {  id:  194, name:  'Zimbabwe' }
];
