import { State } from './state';

export const States: State[] = [
    { id: 1, stateName:  'Alabama', stateAbbrev: 'AL' },
    { id: 2, stateName:  'Alaska', stateAbbrev: 'AK' },
    { id: 3, stateName:  'Arizona', stateAbbrev: 'AZ' },
    { id: 4, stateName:  'Arkansas', stateAbbrev: 'AR' },
    { id: 5, stateName:  'California', stateAbbrev: 'CA' },
    { id: 6, stateName:  'Colorado', stateAbbrev: 'CO' },
    { id: 7, stateName:  'Connecticut', stateAbbrev: 'CT' },
    { id: 8, stateName:  'Delaware', stateAbbrev: 'DE' },
    { id: 9, stateName:  'District of Columbia', stateAbbrev: 'DC' },
    { id: 10, stateName:  'Florida', stateAbbrev: 'FL' },
    { id: 11, stateName:  'Georgia', stateAbbrev: 'GA' },
    { id: 12, stateName:  'Hawaii', stateAbbrev: 'HI' },
    { id: 13, stateName:  'Idaho', stateAbbrev: 'ID' },
    { id: 14, stateName:  'Illinois', stateAbbrev: 'IL' },
    { id: 15, stateName:  'Indiana', stateAbbrev: 'IN' },
    { id: 16, stateName:  'Iowa', stateAbbrev: 'IA' },
    { id: 17, stateName:  'Kansas', stateAbbrev: 'KS' },
    { id: 18, stateName:  'Kentucky', stateAbbrev: 'KY' },
    { id: 19, stateName:  'Louisiana', stateAbbrev: 'LA' },
    { id: 20, stateName:  'Maine', stateAbbrev: 'ME' },
    { id: 21, stateName:  'Maryland', stateAbbrev: 'MD' },
    { id: 22, stateName:  'Massachusetts', stateAbbrev: 'MA' },
    { id: 23, stateName:  'Michigan', stateAbbrev: 'MI' },
    { id: 24, stateName:  'Minnesota', stateAbbrev: 'MN' },
    { id: 25, stateName:  'Mississippi', stateAbbrev: 'MS' },
    { id: 26, stateName:  'Missouri', stateAbbrev: 'MO' },
    { id: 27, stateName:  'Montana', stateAbbrev: 'MT' },
    { id: 28, stateName:  'Nebraska', stateAbbrev: 'NE' },
    { id: 29, stateName:  'Nevada', stateAbbrev: 'NV' },
    { id: 30, stateName:  'New Hampshire', stateAbbrev: 'NH' },
    { id: 31, stateName:  'New Jersey', stateAbbrev: 'NJ' },
    { id: 32, stateName:  'New Mexico', stateAbbrev: 'NM' },
    { id: 33, stateName:  'New York', stateAbbrev: 'NY' },
    { id: 34, stateName:  'North Carolina', stateAbbrev: 'NC' },
    { id: 35, stateName:  'North Dakota', stateAbbrev: 'ND' },
    { id: 36, stateName:  'Ohio', stateAbbrev: 'OH' },
    { id: 37, stateName:  'Oklahoma', stateAbbrev: 'OK' },
    { id: 38, stateName:  'Oregon', stateAbbrev: 'OR' },
    { id: 39, stateName:  'Pennsylvania', stateAbbrev: 'PA' },
    { id: 40, stateName:  'Rhode Island', stateAbbrev: 'RI' },
    { id: 41, stateName:  'South Carolina', stateAbbrev: 'SC' },
    { id: 42, stateName:  'South Dakota', stateAbbrev: 'SD' },
    { id: 43, stateName:  'Tennessee', stateAbbrev: 'TN' },
    { id: 44, stateName:  'Texas', stateAbbrev: 'TX' },
    { id: 45, stateName:  'Utah', stateAbbrev: 'UT' },
    { id: 46, stateName:  'Vermont', stateAbbrev: 'VT' },
    { id: 47, stateName:  'Virginia', stateAbbrev: 'VA' },
    { id: 48, stateName:  'Washington', stateAbbrev: 'WA' },
    { id: 49, stateName:  'West Virginia', stateAbbrev: 'WV' },
    { id: 50, stateName:  'Wisconsin', stateAbbrev: 'WI' },
    { id: 51, stateName:  'Wyoming', stateAbbrev: 'WY' },
    { id: 52, stateName:  'Alberta', stateAbbrev: 'AB' },
    { id: 53, stateName:  'British Columbia', stateAbbrev: 'BC' },
    { id: 54, stateName:  'Manitoba', stateAbbrev: 'MB' },
    { id: 55, stateName:  'Newfoundland', stateAbbrev: 'NL' },
    { id: 56, stateName:  'New Brunswick', stateAbbrev: 'NB' },
    { id: 57, stateName:  'Nova Scotia', stateAbbrev: 'NS' },
    { id: 58, stateName:  'Northwest Territories', stateAbbrev: 'NT' },
    { id: 59, stateName:  'Nunavut', stateAbbrev: 'NU' },
    { id: 60, stateName:  'Ontario', stateAbbrev: 'ON' },
    { id: 61, stateName:  'Prince Edward Island', stateAbbrev: 'PE' },
    { id: 62, stateName:  'Quebec', stateAbbrev: 'QC' },
    { id: 63, stateName:  'Saskatchewan', stateAbbrev: 'SK' },
    { id: 64, stateName:  'Yukon Territory', stateAbbrev: 'YT' }
];
