import { Member } from './member';

export const Members: Member[] = [
    {
      id: 13,
      lastName: 'Thorn',
      firstName: 'Chris',
      middleName: null,
      suffix: null,
      address1: '1601S. Jackson',
      address2: '',
      address3: null,
      city: 'Joplin',
      stateId: 26,
      countryId: 185,
      postalCode: 64804,
      homePhone: '-417',
      cellPhone: '',
      email: null,
      dob: new Date('1976-01-01'),
      dojoId: 11,
      memberTypeId: 3,
      dateJoined: new Date('1994-07-01'),
      dateOfRank: new Date('2002-11-23'),
      rankText: '2nd Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: new Date('2008-11-01'),
      comments: ''
    },
    {
      id: 53,
      lastName: 'Morris',
      firstName: 'Kevin',
      middleName: null,
      suffix: null,
      address1: 'P.O. Box 628',
      address2: null,
      address3: null,
      city: 'Hydesville',
      stateId: 5,
      countryId: 185,
      postalCode: 95547,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: new Date('1956-01-01'),
      dojoId: 24,
      memberTypeId: 3,
      dateJoined: new Date('1990-10-01'),
      dateOfRank: new Date('2008-06-01'),
      rankText: '7th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: new Date('2013-10-01'),
      comments: null
    },
    {
      id: 63,
      lastName: 'Logan',
      firstName: 'Glen',
      middleName: null,
      suffix: null,
      address1: '11702 E Freedom Dr',
      address2: '',
      address3: null,
      city: 'Clarmore',
      stateId: 37,
      countryId: 185,
      postalCode: 74017,
      homePhone: '918-275-4380',
      cellPhone: '',
      email: null,
      dob: new Date('1952-01-01'),
      dojoId: 34,
      memberTypeId: 3,
      dateJoined: new Date('1991-04-01'),
      dateOfRank: new Date('2003-01-01'),
      rankText: '6th Dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: new Date('2011-04-01'),
      comments: ''
    },
    {
      id: 66,
      lastName: 'Mead',
      firstName: 'Harold J',
      middleName: null,
      suffix: null,
      address1: '46387 451st Ave',
      address2: null,
      address3: null,
      city: 'Nicollet',
      stateId: 24,
      countryId: 185,
      postalCode: 56074,
      homePhone: null,
      cellPhone: null,
      email: null,
      dob: new Date('1945-01-01'),
      dojoId: 284,
      memberTypeId: 2,
      dateJoined: new Date('1991-03-20'),
      dateOfRank: new Date('2013-06-01'),
      rankText: '10th dan',
      isActive: true,
      dateInactive: null,
      dateLastPaid: new Date('2011-02-01'),
      comments: null
    }
  ];
